### ISSUE TITLE
Integrate with PagerDuty for Alerts

### ISSUE THREAD

**Issue by aisegfault** [covid-alert-ny/covid-green-infra#11]
Integrate with PagerDuty for Alerts

**Comment by erhudy** [comment]
The PagerDuty trial account has expired, so if we want to use it we'll have to re-up. New Relic has basic alerting in the form of e-mail and we could use an e-mail to SMS gateway if desired but it's not as sophisticated as PD.

**Comment by aisegfault** [comment]
done
