### ISSUE TITLE
It seems the backend infra was designed for 1 AZ/1 region deployment

### ISSUE THREAD

**Issue by aisegfault** [covid-alert-ny/covid-green-infra#5]
For high availability and DR-1 we need to deploy in production with more than 1 AZ and at least 1 extra region.  Fiacc as discussed please follow on this issue.

**Comment by dgonzalez** [comment]
Hi!

The backend is designed to be deployed into all the available zones in a given region (and it currently is)
The database itself is AuroraDB with point in time recovery which provides a very short window of data loss (regarding disaster recovery).

Happy to discuss more about this but deploying the data layer across more than one region would require significant changes into the infrastructure.

**Comment by aisegfault** [comment]
at a minimum muli-regional RDS - active/passive replication

**Comment by segfault** [comment]
We're now using a multi-AZ replica for RDS. Regional failure will be addressed in #20
